### PR TITLE
Clean up version-dependent behavior

### PR DESCRIPTION
**Pull request by tkelman**

### CODE REVIEW

**Comment by tkelman** [comment]
cc @montyvesselinov do you not get notifications for issues or PR's ?

**Comment by montyvesselinov** [comment]
Merged

**Comment by tkelman** [comment]
Thanks!

**Comment by montyvesselinov** [comment]
i was busy. i missed it.

-monty

**Comment by montyvesselinov** [comment]
how to address .!(B) in v0.5 and v0.6

WARNING: !(B::BitArray) is deprecated, use .!(B) instead

**Comment by tkelman** [comment]
maybe `map(!, B)` ?

**Pull request merged**
